# Generated by Django 5.0.6 on 2024-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codehack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
